import { useState } from "react";
import Dashboard from "./components/Dashboard/Dashboard";
import SideBar from "./components/SideBar/SideBar";

const EXAMPLE_PEOPLE = [
  {
    id: Math.random(),
    firstName: "Alonso",
    lastName: "Briones",
    company: "Test Company",
    title: "",
    email: "alonso@gmail.com",
    phone: "1234567890",
    ownedBy: "Luis Perez",
    street: "123 Main St",
    created: "5/3/2022",
    lastContacted: "9/1/2022",
    image: "https://picsum.photos/200/200",
  },
  {
    id: Math.random(),
    firstName: "John",
    lastName: "Smith",
    company: "Test Company",
    title: "",
    email: "john@yahoo.com",
    phone: "1234567890",
    ownedBy: "Alonso Briones",
    street: "123 Main St",
    created: "5/3/2022",
    lastContacted: "9/1/2022",
    image: "https://picsum.photos/200/200",
  },
  {
    id: Math.random(),
    firstName: "Luis",
    lastName: "Williams",
    company: "Test Company",
    title: "",
    email: "luis@outlook.com",
    phone: "1234567890",
    ownedBy: "",
    street: "123 Main St",
    created: "5/3/2022",
    lastContacted: "9/1/2022",
    image: "https://picsum.photos/200/200",
  },
  {
    id: Math.random(),
    firstName: "John",
    lastName: "Smith",
    company: "Test Company",
    title: "",
    email: "john@yahoo.com",
    phone: "1234567890",
    ownedBy: "Alonso Briones",
    street: "123 Main St",
    created: "5/3/2022",
    lastContacted: "9/1/2022",
    image: "https://picsum.photos/200/200",
  },
  {
    id: Math.random(),
    firstName: "Alonso",
    lastName: "Briones",
    company: "Test Company",
    title: "",
    email: "alonso@gmail.com",
    phone: "1234567890",
    ownedBy: "Luis Perez",
    street: "123 Main St",
    created: "5/3/2022",
    lastContacted: "9/1/2022",
    image: "https://picsum.photos/200/200",
  },
  {
    id: Math.random(),
    firstName: "John",
    lastName: "Smith",
    company: "Test Company",
    title: "",
    email: "john@yahoo.com",
    phone: "1234567890",
    ownedBy: "Alonso Briones",
    street: "123 Main St",
    created: "5/3/2022",
    lastContacted: "9/1/2022",
    image: "https://picsum.photos/200/200",
  },
  {
    id: Math.random(),
    firstName: "John",
    lastName: "Smith",
    company: "Test Company",
    title: "Suppervisor",
    email: "john@yahoo.com",
    phone: "1234567890",
    ownedBy: "Alonso Briones",
    street: "123 Main St",
    created: "5/3/2022",
    lastContacted: "9/1/2022",
    image: "https://picsum.photos/200/200",
  },
  {
    id: Math.random(),
    firstName: "Alonso",
    lastName: "Briones",
    company: "Test Company",
    title: "",
    email: "alonso@gmail.com",
    phone: "1234567890",
    ownedBy: "Luis Perez",
    street: "123 Main St",
    created: "5/3/2022",
    lastContacted: "9/1/2022",
    image: "https://picsum.photos/200/200",
  },
  {
    id: Math.random(),
    firstName: "Alonso",
    lastName: "Briones",
    company: "Test Company",
    title: "",
    email: "alonso@gmail.com",
    phone: "1234567890",
    ownedBy: "Luis Perez",
    street: "123 Main St",
    created: "5/3/2022",
    lastContacted: "9/1/2022",
    image: "https://picsum.photos/200/200",
  },
  {
    id: Math.random(),
    firstName: "John",
    lastName: "Smith",
    company: "Test Company",
    title: "Manager",
    email: "john@yahoo.com",
    phone: "1234567890",
    ownedBy: "Alonso Briones",
    street: "123 Main St",
    created: "5/3/2022",
    lastContacted: "9/1/2022",
    image: "https://picsum.photos/200/200",
  },
  {
    id: Math.random(),
    firstName: "Luis",
    lastName: "Williams",
    company: "Test Company",
    title: "",
    email: "luis@outlook.com",
    phone: "1234567890",
    ownedBy: "",
    street: "123 Main St",
    created: "5/3/2022",
    lastContacted: "9/1/2022",
    image: "https://picsum.photos/200/200",
  },
];

function App() {
  const [people, setPeople] = useState(EXAMPLE_PEOPLE);

  return (
    <div>
      <SideBar />
      <Dashboard people={people} />
    </div>
  );
}

export default App;
